### ISSUE TITLE
PACKAGES: mod-ion working on Desktop

### ISSUE THREAD

**Issue by winwisely99** [getcouragenow/packages#129]
this under development: https://github.com/pion/ion/pull/41

It almost works. 
- we need to do an integration ASAP so we can feedback to them aout what they got wrong before its too late
- I think IDIR

Desktop can do video or audio.
SO we just put the go-astilectron inside the go-flutter dekstop.
- should be easy.

so when a user is using ion and they click to open an video conf, we just open a the go-astilectron  from inside the go-flutter.

**Comment by winwisely99** [comment]
This is expected because ions dependencies cant work for desktop.

````
apple@x-MacBook-Pro client % make flu-desk-run
fatal: No names found, cannot describe anything.
#cd /Users/apple/workspace/go/src/github.com/winwisely99/packages/maintemplate/client/ && hover init
cd /Users/apple/workspace/go/src/github.com/winwisely99/packages/maintemplate/client/ && hover run
hover: Using engine from cache
hover: Cleaning the build directory
hover: ⚠ The go-flutter project tries to stay compatible with the beta channel of Flutter.
hover: ⚠     It's advised to use the beta channel: `flutter channel beta`
hover: Bundling flutter app
Running "flutter pub get" in client...                              9.8s

Compiler message:
../../../../../../../../.pub-cache/hosted/pub.dartlang.org/ima
ge_picker_web-0.1.6/lib/src/web_image_picker.dart:2:8: Error:
Not found: 'dart:html'
import 'dart:html' as html;
       ^
../../mod-chat/client/lib/grpc_web_example/api/chat_service.da
rt:117:53: Error: The argument type 'StringValue' can't be
assigned to the parameter type 'ReqMessage'.
 - 'StringValue' is from
 'package:mod_chat/grpc_web_example/api/v1/google/protobuf/wra
 ppers.pb.dart'
 ('../../mod-chat/client/lib/grpc_web_example/api/v1/google/pr
 otobuf/wrappers.pb.dart').
 - 'ReqMessage' is from
 'package:mod_chat/grpc_web_example/api/v1/chat.pb.dart'
 ('../../mod-chat/client/lib/grpc_web_example/api/v1/chat.pb.d
 art').
          await grpc.ChatServiceClient(client).send(request);
                                                    ^
../../../../../../../../.pub-cache/hosted/pub.dartlang.org/ima
ge_picker_web-0.1.6/lib/src/web_image_picker.dart:7:16: Error:
'FileUploadInputElement' isn't a type.
    final html.FileUploadInputElement input =
    html.FileUploadInputElement();
               ^^^^^^^^^^^^^^^^^^^^^^
../../../../../../../../.pub-cache/hosted/pub.dartlang.org/ima
ge_picker_web-0.1.6/lib/src/web_image_picker.dart:7:47: Error:
Method not found: 'FileUploadInputElement'.
    final html.FileUploadInputElement input =
    html.FileUploadInputElement();
                                              ^^^^^^^^^^^^^^^^
                                              ^^^^^^
../../../../../../../../.pub-cache/hosted/pub.dartlang.org/ima
ge_picker_web-0.1.6/lib/src/web_image_picker.dart:12:20:
Error: Method not found: 'FileReader'.
    final reader = html.FileReader();
                   ^^^^^^^^^^
../../../../../../../../.pub-cache/hosted/pub.dartlang.org/ima
ge_picker_web-0.1.6/lib/src/web_image_picker.dart:31:16:
Error: 'FileUploadInputElement' isn't a type.
    final html.FileUploadInputElement input =
    html.FileUploadInputElement();
               ^^^^^^^^^^^^^^^^^^^^^^
../../../../../../../../.pub-cache/hosted/pub.dartlang.org/ima
ge_picker_web-0.1.6/lib/src/web_image_picker.dart:31:47:
Error: Method not found: 'FileUploadInputElement'.
    final html.FileUploadInputElement input =
    html.FileUploadInputElement();
                                              ^^^^^^^^^^^^^^^^
                                              ^^^^^^
../../../../../../../../.pub-cache/hosted/pub.dartlang.org/ima
ge_picker_web-0.1.6/lib/src/web_image_picker.dart:36:20:
Error: Method not found: 'FileReader'.
    final reader = html.FileReader();
                   ^^^^^^^^^^
../../../../../../../flutter/packages/flutter_web_plugins/lib/
src/plugin_registry.dart:29:5: Error: Method not found:
'webOnlySetPluginHandler'.
    ui.webOnlySetPluginHandler(_binaryMessenger.handlePlatform
    Message);
    ^^^^^^^^^^^^^^^^^^^^^^^
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:dart%3
Ahtml; message=StandardFileSystem only supports file:* and
data:* URIs)
#0      StandardFileSystem.entityForUri
(package:front_end/src/api_prototype/standard_file_system.dart
:33:7)
#1      asFileUri (package:vm/kernel_front_end.dart:584:37)
<asynchronous suspension>
#2      writeDepfile (package:vm/kernel_front_end.dart:779:21)
<asynchronous suspension>
#3      FrontendCompiler.compile
(package:frontend_server/frontend_server.dart:479:15)
<asynchronous suspension>
#4      _FlutterFrontendCompiler.compile
(package:flutter_frontend_server/server.dart:38:22)
#5      starter
(package:flutter_frontend_server/server.dart:162:27)
#6      main
(file:///b/s/w/ir/cache/builder/src/flutter/flutter_frontend_s
erver/bin/starter.dart:8:30)
#7      _startIsolate.<anonymous closure>
(dart:isolate-patch/isolate_patch.dart:299:32)
#8      _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:168:12)


Target kernel_snapshot failed: Exception: Errors during
snapshot creation: null
Failed to build bundle.
hover: Flutter build failed: exit status 1
make: *** [flu-desk-run] Error 1
apple@x-MacBook-Pro client % make flu-web-run 

````
